--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xerenahmed/ListenerExtended
build-by-default: true
branches:
- main
projects:
  ListenerExtended:
    path: ""
    model: virion
    type: library
...
