name: CI
on:
  - push
  - pull_request
jobs:
  phpstan:
    name: phpstan analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0.11"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@e232f72a4330a07aae8418e8aa56b64efcdda636
        with:
          php-version: ${{matrix.php-version}}
          install-path: "./dev/bin"
      - name: phpstan analyze
        run: php -dphar.readonly=0 -dmemory_limit=256M vendor/bin/phpstan analyze
  fmt:
    name: code style check
    needs: [phpstan]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0.11"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@e232f72a4330a07aae8418e8aa56b64efcdda636
        with:
          php-version: ${{matrix.php-version}}
          install-path: "./dev/bin"
      - run: php vendor/bin/php-cs-fixer fix --dry-run --diff
